### ISSUE TITLE
META - High-Level Roadmap with DAG(s)

### ISSUE THREAD

**Issue by moul** [atomone-hub/genesis#50]
The purpose of this issue is to reference and update high-level DAGs that can serve as indexes for navigating topics, like Compendium (#42).

Moderator (@atomone-hub/mod)  who have write permissions should keep the top-level DAGs updated according to the comments below. This allows anyone to suggest changes, ensuring that the DAGs are always up to date.

## Eras / Milestones

```mermaid
timeline
    title AtomOne Hub Milestones
    Phase 1 - Pre-IBC   			: Define Constitution
                       			    			: Launch Governance-Only Chain
    Phase 2 - Post-IBC 			: $PHOTON with Auto-Staking
                                       			: Fix Validator Incentives
                                       			: Implement ICS1.5
                                       			: Prototypes with SubDAOs (including GNO)
    Phase 3 - ICS1.5 Scaling 	: Migrate $PHOTON to ICS
                                                 	: Promote Smart Contract Use Cases
                                                 	: Develop Scalable Validator Infrastructure
                                                 	: Develop Recovery Procedures
    Phase 4 - Maintenance   	: Create OnChain Education Curriculum
                                              	: Promote Good Forks and Projects
                                              	: Promote Other Common Goods
                                              	: Finalize the Software
```

## AtomOne Phase 1 - Pre-IBC's Tasks (current focus)

_Phase 1 High-Level Roadmap. Please include links to issues, preferably a single meta issue, whenever available._

- [ ] Define Constitution
 	- [ ] Choose License(s) for this repo (#49)
	- [ ] Branding & Legal
	- [ ] Complete the CONSTITUTION w/ all known functionality
	- [ ] Reconcile this README with CONSTITUTION
	- [ ] Incorporate the "Constitutional Majority" in the Constitution.
	- [ ] Move Decentralists governance roadmap here.
	- [ ] Keplr & Ledger need competition.
	- [ ] Consider referencing https://twitter.com/jaekwon/status/1724641822398681547 with more insight.
	- [ ] Roadmap Timeline
	- [ ] Links to Additional Resources such as technical documentation, or community forums, for in-depth information.
	- [ ] Channels for reaching out to the core team or support, especially for technical support or collaboration inquiries.
	- [ ] Scan through twitter posts for more ideaas.
	- [ ] Argument for why hub and spokes are needed (from atom one)
	- [ ] Quantum resistance
	- [ ] Constitution updates: $ATOM -> $ATOM1; Add $phATOM and $phATOM1; conversion
	- [ ] At least one week for decentralists feedback on proposals that meet the spam threshold.
	- [ ] Proposals should be self contained no PDF necessary.
	- [ ] TM2 Consensus Court
	- [ ] Subsidize relayers and require payment for every IBC tx.
	- [ ] Fork proves that slashing is real.
	- [ ] Increased Voting Period.
	- [ ] Globally decentralized validator set.
	- [ ] What is a hub? connected zones and shards should use it as such, not make more connections out.
	- [ ] Allow the staking distribution to hone its intelligence via slashing.
	- [ ] Use real human connections to defend against AI.
	- [ ] About diversity of implementation, and its limitations.
	- [ ] Add old PHOTON elements back in if relevant; not counting 2/3 ratio...
	- [ ] Recovery procedure by AtomOne in the case of IBC zone failure.
	- [ ] Recovery procedure by AtomOne in the case of ICS shard failure.
	- [ ] Require the ICF to buy back ATOMs and to allocate them for on-chain disbursement.
	- [ ] Indemnify all actors given no malice outside of the chain. Allow the chain to enforce penalties from outside the chain.
	- [ ] Specify that $ATOM1 held in pools and bonded for $phATOM1 do not count toward the bond ratio.
	- [ ] Add rules for what non-hubs and hubs (separate rules) must abide by. Not all hubs can connect due to this.
	- [ ] XXX
- [ ] Launch Governance-Only Chain
	- [ ] Prepare Genesis
		- [ ] Snapshot Cosmos-Hub4 (balances, votes) (#18)
		- [ ] Define Airdrop rules
		- [ ] Generate Genesis
	- [ ] Prepare Software
		- [ ] Choose Software Target (#17)
		- [ ] Fork & Cleanup
		- [ ] Develop/adapt modules
			- [ ] Governance improvements (#45)
			- [ ] XXX
		- [ ] Configure native tokens
	- [ ] Run Testnets
		- [ ] Coordinate validators
		- [ ] Run testnets
		- [ ] Organize testing sessions
	- [ ] Prepare Mainnet Launch
		- [ ] XXX

**Comment by moul** [comment]
Okay, I have closed issue #51 to maintain the TODO in the README.

I propose that we use this meta issue for other matters like graphical visualization, but I recommend having a single source of truth, which is the README.

Would you like to keep the current unsorted flat list, or should I create a PR to suggest this tree structure with checkboxes in the README instead?
